version: '3'

services:
  db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=jobsite-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    volumes:
      - mariadb_data:/var/lib/mysql
    #ports:
    #  - "3306:3306"

  server:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/code
    #ports:
    #  - "8009:8000"
    depends_on:
      - db

  client:
    build: npm install
    command: npm run dev
    #volumes:
    #  - .:/code
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  mariadb_data: